### ISSUE TITLE
JQuery version update in Drupal

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#16]
This is arising from the conversation @ https://github.com/cwrc/Islandora-CWRC-Writer/issues/15#

@bradklaver , how difficult would it be for Digital Echidna to update the JQuery version used by Drupal to match the version used by CWRC-Writer (i.e. JQuery 1 to JQuery 3). If this is something that could be done with reasonable time constraints, then deployed as a Drupal module, it could be beneficial to any other users who run into a similar compatibility issue.

**Comment by jchartrand** [comment]
Is this different than what Andrew describes in the issue he just created here:

https://github.com/cwrc/CWRC-WriterBase/issues/25 <https://github.com/cwrc/CWRC-WriterBase/issues/25>

Or is this meant to be assigned to Brad?

**Comment by ajmacdonald** [comment]
This is an alternate approach to the same problem.

**Comment by ilovan** [comment]
Precisely, as we mentioned in the CWRC-Writer meeting we had earlier this morning, if such a swap is possible on the Echidna side is possible and packageable into a Drupal module - it could be useful to other Drupal users trying to install CWRC-Writer in their environment or even needing the more recent version of JQuery for other purposes.

This is a question for Brad, but I assigned James and Andrew to it as well to ensure they are in the loop with whatever the answer is.

**Comment by SusanBrown** [comment]
Created a Trello card to ensure that Brad/Digital Echidna is aware of this.

**Comment by ajmacdonald** [comment]
Hi all, I've pretty much resolved this issue.

**Comment by SusanBrown** [comment]
Terrific!



On Dec 20, 2017, at 5:49 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all, I've pretty much resolved this issue.
