### ISSUE TITLE
dev-05 version: can't tag any entity inside a specific paragraph

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#22]
![Screen Shot 2018-02-05 at 10.10.43 AM.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/4682806b-ad72-4fb3-9a90-0cb433d4ece1)

This is the document: https://cwrc-dev-05.srv.ualberta.ca/islandora/object/cwrc%3A7184b9ef-7cf8-42c9-bd53-f16036bb2e36/edit-cwrc#cwrc:7184b9ef-7cf8-42c9-bd53-f16036bb2e36

No issues adding entity references to the paragraph before it or the paragraph after. 

The only clue why this paragraph may be different is that before trying to tag entities inside it, I pasted the paragraph before it a couple of times in a row, then used the delete key on my keyboard to delete the two extra identical paragraphs (which kind of brought this paragraph on the spot where the deleted paragraphs were sitting?)

**Comment by ajmacdonald** [comment]
Somehow the "current tag" was lost. This is why in the error it says "not a valid child of null".

@ilovan do you recall more precisely what was involved in the pasting and deleting process? This will help me to recreate the issue.

**Comment by ilovan** [comment]
I can't reproduce this anymore so will "freeze" it for now
