### ISSUE TITLE
Glitch in the interaction between CWRC-Writer and the collapsable sidebar in CWRC

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#23]
![feb-18-2018 02-54-00](https://user-images.githubusercontent.com/6600070/36350555-4ebe91c0-1457-11e8-94ad-3ec7dba52b7d.gif)

**Comment by ajmacdonald** [comment]
@SusanBrown I looked into adding handling for this on the cwrc-writer side but it's difficult & inefficient to detect when the parent element for the cwrc-writer changes size. If someone on the Islandora side could add this to the code for when that sidebar button is pressed, it will fix the issue:
```
Drupal.CWRCWriter.writer.layoutManager.resizeAll();
```

**Comment by ilovan** [comment]
Thanks, @ajmacdonald , does it make sense for you to send this to Echidna as a pull request? If not, I will ask Brad to take over this issue.

**Comment by ajmacdonald** [comment]
@ilovan I would if I knew where in the code the handling for the sidebar button was. I couldn't easily find it.

**Comment by ilovan** [comment]
I thought as much. 

@bradklaver , could you please take over and put in the code that @ajmacdonald suggests.

**Comment by ilovan** [comment]
work complete and deployed
