### ISSUE TITLE
Side-by-side versions should have all three panels expanded by default in the Reader view, even if very narrow. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#24]
@SusanBrown what's your take on this?

<img width="1171" alt="screen shot 2018-02-18 at 3 29 05 am" src="https://user-images.githubusercontent.com/6600070/36350820-e89381bc-145b-11e8-8a62-8ef130b839e7.png">

**Comment by SusanBrown** [comment]
I guess so, but it's pretty cramped. 

I think two things: 
1) we need a means of closing the image view window. If there isn't an issue for this year, pls create one. And then we need a means of opening it again of course.
2) we should look at modifying the CWRC-Writer module to have the right panel for bookmarking etc. closed by default.

**Comment by ajmacdonald** [comment]
@SusanBrown panels can be closed by clicking on the arrow image at the centre of each panel divider/resizer

**Comment by SusanBrown** [comment]
Yes, I don't know what went on at the time but it's fine now.
