### ISSUE TITLE
Integrated CWRC-Writer: radio buttons in all dialogs are not rendering the label when selected

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#29]
![screen shot 2018-05-10 at 3 03 58 pm](https://user-images.githubusercontent.com/6600070/39894231-6824c8fe-5463-11e8-86bb-7b2dfc135604.png)

@ajmacdonald , could you look at this as soon as possible, rectify in dev-06 and let me know what commit should Brad pull into the CWRC beta code to apply this fix (we installed the new CWRC_Writer there this morning)

**Comment by ajmacdonald** [comment]
In general there are multiple conflicts between the css for cwrc-writer and the de_theme.css used by Islandora (another e.g. https://github.com/cwrc/Islandora-CWRC-Writer/issues/30#issuecomment-388850067 ). It would be worth having a conversation with the Islandora team about how to best resolve this.

**Comment by SusanBrown** [comment]
We are certainly seeing evidence of this in our testing. For instance, the right click menu on entities in the entity panel has now dropped down far to the left, on to of the main editing panel, and so has apparently disappeared entirely.

It would be great if you and @bradklaver or Luke at Digital Echidna could connect about this asap to try to figure out how to handle it.

**Comment by bradklaver** [comment]
Having a look at this.

**Comment by bradklaver** [comment]
Fixed on test

**Comment by ilovan** [comment]
fixed on Beta
![image](https://user-images.githubusercontent.com/6600070/47919276-9a3c0f00-de74-11e8-966c-c2d7336faf4a.png)

Thank you , @bradklaver
