### ISSUE TITLE
CWRC beta: User below admin cannot save graphic image URL attributes or any other attributes

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#33]

**Comment by ilovan** [comment]
Admins can do it from the "edit source panel"

**Comment by ajmacdonald** [comment]
Ah. I broke how validation works when I started adding full names to attributes in the form.
@ilovan @SusanBrown I just want to confirm that we're still allowing the user to add tags even if they're missing required attributes, e.g. graphic and the url attribute

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/3aa29259828d86a805f461f9d4d18d22c74f6708

**Comment by ilovan** [comment]
I think that as long as the validation check tells them that the document is not valid, that's OK. 
Alternatively, could you set up a warning message when someone tries to save a tag without the required attribute (or with an "empty" attribute for that matter)

**Comment by SusanBrown** [comment]
I think for now as Mihaela says that it’s ok, and we can see if users want a warning.


On Jun 5, 2018, at 12:57 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that as long as the validation check tells them that the document is not valid, that's OK.
Alternatively, could you set up a warning message when someone tries to save a tag without the required attribute (or with an "empty" attribute for that matter)

**Comment by ilovan** [comment]
@ajmacdonald 
you put this in the QA 1 pipeline. 
not sure where you want me to test it? In dev-06? 
It's not been implemented in CWRC beta yet (that's for sure)

**Comment by ilovan** [comment]
work complete and deployed
