### ISSUE TITLE
Integrated CWRC-Writer: Tag citation produces what apparently looks like a TEI entity forms error, even when tagging a citation to an existing CWRC title entity

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#38]
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/b84b0528-bb96-425b-ac36-f0ff1d938513)

**Comment by ajmacdonald** [comment]
The schema entries that are being added to `Drupal.settings.CWRCWriter.schemas` have the wrong URLs in the `entityTemplates` property. For example in:
```
{
    "pid":"cwrc:13d0b3bf-4d37-4ead-bb05-c91260233532",
    "name":"CWRC TEI Lite",
    "schemaMappingsId":"tei",
    "entityTemplates": {
        "note":"https://dev-02.cwrc.ca/sites/default/modules/islandora_cwrc_writer/build/schema/tei/xml/js/schema/tei/xml/note.xml",
        "citation":"https://dev-02.cwrc.ca/sites/default/modules/islandora_cwrc_writer/build/schema/tei/xml/js/schema/tei/xml/citation.xml"
    },
    "url":"https://cwrc.ca/schemas/cwrc_tei_lite.rng",
    "aliases":["https://cwrc.ca/schemas/cwrc_tei_lite.rng"],
    "cssUrl":"https://cwrc.ca/templates/css/tei.css"
}
```

https://dev-02.cwrc.ca/sites/default/modules/islandora_cwrc_writer/build/schema/tei/xml/js/schema/tei/xml/citation.xml
should be
https://dev-02.cwrc.ca/sites/default/modules/islandora_cwrc_writer/build/schema/tei/xml/citation.xml

**Comment by ilovan** [comment]
This is the object:
https://dev-02.cwrc.ca/islandora/object/cwrc%3Aee971945-ab2a-4d3e-a1f5-6a2378a1ef40

As you can see, it's a TEI document created from template (Sample letter), so it's a CWRC TEI Lite object

The problem I am having is with the fact that, in the process of tagging a citation, I already chose an existing CWRC title entity, yet I get this error message, as if I am attempting to create a new title entity.

Note that we don't have new entity forms for creating title entities:
In the new CWRC_Writer lookups, if the user wants to create a new title entity, they are redirected to the CWRC  Drupal interface to create the title there.

**Comment by jefferya** [comment]
Why is the example not using cwrc:teiLiteSchema (from the default list of schemas visiable in the solution pack config screen)? Only the default schemas on the dev server were fixed. Do all schemas need to be repaired on the dev server (they weren't to save time)? The example object is not using a fixed schema object.

**Comment by ajmacdonald** [comment]
I just tried adding a CWRC Document using the Sample TEI Letter template on dev-02. It seems to be associated with the schemaId `cwrc:13d0b3bf-4d37-4ead-bb05-c91260233532`. I don't know why it isn't associated with `cwrc:teiLiteSchema`.

**Comment by ilovan** [comment]
That is on me to fix, as soon as you point me to the location of the Islandora-integrated CWRC-Writer templates location in GitHUb (since the templates are added to Fedora with the installation of the  Islandora wrapper of the CWRC_Writer, I am assuming they are stored somewhere in the Islandora CWRC_Writer code (I think changing the Fedora version of the templates would be over-written next time we update the CWRC-Writer code in Islandora, correct, @ajmacdonald )

**Comment by ilovan** [comment]
Decission : afer talking to @ajmacdonald , will ask @nikathone for help.

**Comment by jefferya** [comment]
@ilovan All that should be needed is to reingest the template via the solution pack admin page. The source code always used a human-readable PID.

**Comment by ilovan** [comment]
Thanks, @jefferya , will do as you suggest.

**Comment by ilovan** [comment]
Right again, @jefferya . Problem fixed. Thanks.
