### ISSUE TITLE
Isnadora-integrated NERVE: ignoring pre-existing entities doesn't seem to work here

### ISSUE THREAD

**Issue by ilovan** [cwrc/Islandora-CWRC-Writer#43]
In the attached PDF, all the pre-existing markup that has been doubled has been highlighted. 

The pdf is based on https://dev-02.cwrc.ca/islandora/object/cwrc%3A619cd15a-8680-4527-877b-ad3a5215fb51

The preexisting entities look odd because they are packed in an old version of the templates that we need to fix. Maybe this is the cause of the problem?

[Islandora%20NERVE-%20automatic%20entity%20recognition%20AND%20manual%20linking.xml copy.pdf](https://github.com/cwrc/Islandora-CWRC-Writer/files/3142597/Islandora.20NERVE-.20automatic.20entity.20recognition.20AND.20manual.20linking.xml.copy.pdf)

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/1c4112e6ebdd5e13a840eb0ff0cda8ca7a46539d

**Comment by ilovan** [comment]
confirmed on prod cwrc.
