### ISSUE TITLE
Islandora can no longer override document schema

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/Islandora-CWRC-Writer#46]
The Islandora CWRC Writer module is referencing an older version of the processDocument method which allowed for schema overriding: https://github.com/cwrc/Islandora-CWRC-Writer/blob/530597d6fece92b441191eb9b94db097f37bd1c2/js/islandora_cwrc_writer.js#L149
That functionality was erroneously removed at this point https://github.com/cwrc/CWRC-WriterBase/commit/b31feda3bcb91701cbb69aeacdfd9f11e35ead3d and needs to be re-added.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/ff0726608027d65dd4548c4bf5c398930117fcb8

**Comment by ilovan** [comment]
is this  pushed to dev-02.cwrc.ca yet, @ajmacdonald ?

**Comment by ajmacdonald** [comment]
Yes it is

**Comment by ilovan** [comment]
confirmed on dev02.cwrc.ca
